CREATE TABLE accounts
(
    id      INT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(100) NOT NULL,
    balance DEC(15, 2)   NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO accounts(name, balance)
VALUES ('Bob', 10000);

BEGIN;

INSERT INTO accounts(name, balance)
VALUES ('Alice', 10000);

SELECT id, name, balance
  FROM accounts;